const express = require('express');
const mysql = require('mysql2');
const cors = require('cors');
const app = express();

// CORS Configuration
const corsOptions = {
  origin: function (origin, callback) {
    // Allow requests with no origin (like mobile apps or curl requests)
    if (!origin || origin === 'http://localhost:3000' || origin === 'http://localhost:5173' || origin.includes('vercel.app') || origin.includes('railway.app')) {
      callback(null, true);
    } else {
      callback(null, true); // Allow all origins for now
    }
  },
  credentials: true,
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization']
};

app.use(cors(corsOptions));
app.use(express.json());
app.options('*', cors(corsOptions)); // Handle preflight requests

const db = mysql.createConnection({
  host: process.env.MYSQLHOST || 'mysql.railway.internal',
  user: process.env.MYSQLUSER || 'root',
  password: process.env.MYSQLPASSWORD || 'lrnexAtnMKgHawwrQGQZQWyspqRXCnQC',
  database: process.env.MYSQLDATABASE || 'washtrack_db',
  port: parseInt(process.env.MYSQLPORT) || 3306,
});

// CONNECTION
db.connect((err) => {
  if (err) {
    console.log('Database connection failed:', err.message);
    console.log('Error code:', err.code);
  } else {
    console.log('Connected to database');
  }
});

// Request logging middleware
app.use((req, res, next) => {
  console.log(`[${new Date().toISOString()}] ${req.method} ${req.path}`);
  console.log('Origin:', req.get('origin'));
  console.log('Content-Type:', req.get('content-type'));
  next();
});

// ROOT ENDPOINT FOR HEALTH CHECK
app.get('/', (req, res) => {
  res.json({ status: 'OK', message: 'WashTrack Backend is running' });
});

// HEALTH CHECK ENDPOINT
app.get('/health', (req, res) => {
  res.json({ status: 'OK', message: 'Server is healthy' });
});

// FOR SIGNUP FUNCTIONALITY
app.post('/signupuser', (req, res) => {
  const { username, password, email, contact, address, isAdmin } = req.body;

  if (isAdmin) {
    // ADMIN REGISTRATION
    const checkEmailSql =
      'SELECT fld_adminID FROM tbl_admin WHERE fld_email = ?';

    db.query(checkEmailSql, [email], (checkErr, emailResult) => {
      if (checkErr) {
        return res.json({
          success: false,
          error: 'Database error: ' + checkErr.message,
        });
      }

      if (emailResult.length > 0) {
        return res.json({
          success: false,
          error: 'Email already exists. Please use a different email address.',
        });
      }

      const sql =
        'INSERT INTO tbl_admin (fld_username, fld_password, fld_email, fld_role) VALUES (?, ?, ?, ?)';

      db.query(sql, [username, password, email, 'Admin'], (err, result) => {
        if (err) {
          res.json({
            success: false,
            error: 'Failed to create admin account: ' + err.message,
          });
        } else {
          const getAdminIdSql =
            'SELECT fld_adminID FROM tbl_admin WHERE fld_email = ?';

          db.query(getAdminIdSql, [email], (getErr, adminResult) => {
            if (getErr || adminResult.length === 0) {
              return res.json({
                success: false,
                error: 'Failed to retrieve admin ID',
              });
            }

            const newAdminId = adminResult[0].fld_adminID;

            res.json({
              success: true,
              message: 'Admin account created successfully!',
              adminId: newAdminId,
            });
          });
        }
      });
    });
  } else {
    // USER REGISTRATION
    const checkEmailSql = 'SELECT fld_userID FROM tbl_user WHERE fld_email = ?';

    db.query(checkEmailSql, [email], (checkErr, emailResult) => {
      if (checkErr) {
        return res.json({
          success: false,
          error: 'Database error: ' + checkErr.message,
        });
      }

      if (emailResult.length > 0) {
        return res.json({
          success: false,
          error: 'Email already exists. Please use a different email address.',
        });
      }

      const sql =
        'INSERT INTO tbl_user (fld_username, fld_password, fld_email, fld_contact) VALUES (?, ?, ?, ?)';

      db.query(sql, [username, password, email, contact], (err, result) => {
        if (err) {
          res.json({
            success: false,
            error: 'Failed to sign up: ' + err.message,
          });
        } else {
          // Get the actual user ID generated by the trigger
          const getUserIdSql =
            'SELECT fld_userID FROM tbl_user WHERE fld_email = ?';

          db.query(getUserIdSql, [email], (getErr, userResult) => {
            if (getErr || userResult.length === 0) {
              return res.json({
                success: false,
                error: 'Failed to retrieve user ID',
              });
            }

            const newUserId = userResult[0].fld_userID;

            // INSERT INTO tbl_registers
            const insertRegisterSql =
              'INSERT INTO tbl_registers (fld_userID) VALUES (?)';
            db.query(insertRegisterSql, [newUserId], (regErr) => {
              if (regErr) {
                console.error(
                  'Failed to create register row for user',
                  newUserId,
                  regErr.message
                );
                return res.json({
                  success: true,
                  message: 'User added but register failed!',
                  userId: newUserId,
                  registerCreated: false,
                  registerError: regErr.message,
                });
              }

              // INSERT INTO tbl_profiles
              const insertAddressSql =
                'INSERT INTO tbl_profiles (fld_userID, fld_address) VALUES (?, ?)';
              db.query(insertAddressSql, [newUserId, address], (addrErr) => {
                if (addrErr) {
                  console.error(
                    'Failed to create address for user',
                    newUserId,
                    addrErr.message
                  );
                  return res.json({
                    success: true,
                    message: 'User and register added, but address failed!',
                    userId: newUserId,
                    registerCreated: true,
                    addressCreated: false,
                    addressError: addrErr.message,
                  });
                }

                res.json({
                  success: true,
                  message: 'User registered successfully!',
                  userId: newUserId,
                  registerCreated: true,
                  addressCreated: true,
                });
              });
            });
          });
        }
      });
    });
  }
});

// FOR ADMIN LOGIN
app.post('/loginadmin', (req, res) => {
  const { email, password } = req.body;

  console.log('Admin login attempt:', { email, password });

  const sql =
    'SELECT fld_adminID, fld_username, fld_email FROM tbl_admin WHERE fld_email = ? AND fld_password = ?';

  db.query(sql, [email, password], (err, result) => {
    if (err) {
      console.log('Database error:', err.message);
      res.json({ success: false, error: 'Login failed: ' + err.message });
    } else {
      console.log('Query result:', result);
      if (result.length > 0) {
        console.log('Admin found:', result[0]);
        res.json({
          success: true,
          message: 'Admin login successful',
          adminID: result[0].fld_adminID,
          user: {
            fld_username: result[0].fld_username,
            fld_email: result[0].fld_email,
            fld_adminID: result[0].fld_adminID,
          },
        });
      } else {
        res.json({ success: false, error: 'Invalid email or password' });
      }
    }
  });
});

// FOR USER LOGIN
app.post('/loginuser', (req, res) => {
  const { email, password } = req.body;

  console.log('User login attempt:', { email: email, password });

  const sql =
    'SELECT fld_userID, fld_username, fld_email, fld_contact FROM tbl_user WHERE fld_email = ? AND fld_password = ?';

  db.query(sql, [email, password], (err, result) => {
    if (err) {
      console.log('Database error:', err.message);
      res.json({ success: false, error: 'Login failed: ' + err.message });
    } else {
      console.log('Query result:', result);
      if (result.length > 0) {
        res.json({
          success: true,
          message: 'User login successful',
          user: {
            fld_username: result[0].fld_username,
            fld_email: result[0].fld_email,
            fld_contact: result[0].fld_contact,
            fld_userID: result[0].fld_userID,
          },
        });
      } else {
        res.json({ success: false, error: 'Invalid email or password' });
      }
    }
  });
});

// FOR GETTING USER DATA AFTER LOGIN
app.get('/getuser/:email', (req, res) => {
  const userEmail = req.params.email;

  const sql =
    'SELECT fld_userID, fld_username, fld_email, fld_contact FROM tbl_user WHERE fld_email = ?';

  db.query(sql, [userEmail], (err, result) => {
    if (err) {
      return res.json({
        success: false,
        error: 'Database error: ' + err.message,
      });
    }

    if (result.length === 0) {
      return res.json({ success: false, error: 'User not found' });
    }

    res.json({ success: true, user: result[0] });
  });
});

// FOR GETTING USER BY ID
app.get('/getuser/id/:userId', (req, res) => {
  const userId = req.params.userId;

  const sql =
    'SELECT fld_userID, fld_username, fld_email, fld_contact FROM tbl_user WHERE fld_userID = ?';

  db.query(sql, [parseInt(userId)], (err, result) => {
    if (err) {
      return res.json({
        success: false,
        error: 'Database error: ' + err.message,
      });
    }

    if (result.length === 0) {
      return res.json({ success: false, error: 'User not found' });
    }

    res.json({ success: true, user: result[0] });
  });
});

// FOR GETTING ALL USERS TO DISPLAY IN ADMIN DASHOBARD
app.get('/allusers', (req, res) => {
  const sql = `
    SELECT 
      u.fld_userID, 
      u.fld_username, 
      u.fld_email, 
      u.fld_contact,
      r.fld_registrationDate
    FROM tbl_user u
    LEFT JOIN tbl_registers r ON u.fld_userID = r.fld_userID
  `;

  db.query(sql, (err, result) => {
    if (err) {
      return res.json({
        success: false,
        error: 'Database error: ' + err.message,
      });
    }

    res.json({ success: true, data: result });
  });
});

// FOR GETTING ADDRESS FROM TBL_PROFILES
app.get('/getprofile/:userId', (req, res) => {
  const userId = req.params.userId;

  const sql = 'SELECT fld_address FROM tbl_profiles WHERE fld_userID = ?';

  db.query(sql, [userId], (err, result) => {
    if (err) {
      return res.json({
        success: false,
        error: 'Database error: ' + err.message,
      });
    }

    if (result.length === 0) {
      return res.json({ success: false, error: 'Profile not found' });
    }

    res.json({ success: true, profile: result[0] });
  });
});

// FOR UPDATING PROFILE ADDRESS
app.put('/updateprofile', (req, res) => {
  const { userId, address } = req.body;

  const sql = `
    INSERT INTO tbl_profiles (fld_userID, fld_address) 
    VALUES (?, ?) 
    ON DUPLICATE KEY UPDATE fld_address = ?
  `;

  db.query(sql, [userId, address, address], (err, result) => {
    if (err) {
      return res.json({
        success: false,
        error: 'Profile update failed: ' + err.message,
      });
    }

    res.json({ success: true, message: 'Profile updated successfully' });
  });
});

// FOR UPDATING PROFILE
app.put('/updateuser', (req, res) => {
  const { email, updates } = req.body;

  const sql =
    'UPDATE tbl_user SET fld_username = ?, fld_contact = ? WHERE fld_email = ?';

  db.query(sql, [updates.fullName, updates.phone, email], (err, result) => {
    if (err) {
      return res.json({
        success: false,
        error: 'Update failed: ' + err.message,
      });
    }

    if (result.affectedRows === 0) {
      return res.json({ success: false, error: 'User not found' });
    }

    res.json({ success: true, message: 'Profile updated successfully' });
  });
});

// FOR VERIFYING OLD PASSWORD
app.post('/verifypassword', (req, res) => {
  const { email, oldPassword } = req.body;

  const sql =
    'SELECT fld_password FROM tbl_user WHERE fld_email = ? AND fld_password = ?';

  db.query(sql, [email, oldPassword], (err, result) => {
    if (err) {
      return res.json({
        success: false,
        error: 'Verification failed: ' + err.message,
      });
    }

    if (result.length === 0) {
      return res.json({ success: false, error: 'Old password is incorrect' });
    }

    res.json({ success: true, message: 'Password verified successfully' });
  });
});

// FOR UPDATING PASSWORD
app.put('/updatepassword', (req, res) => {
  const { email, newPassword } = req.body;

  const sql = 'UPDATE tbl_user SET fld_password = ? WHERE fld_email = ?';

  db.query(sql, [newPassword, email], (err, result) => {
    if (err) {
      return res.json({
        success: false,
        error: 'Password update failed: ' + err.message,
      });
    }

    if (result.affectedRows === 0) {
      return res.json({ success: false, error: 'User not found' });
    }

    res.json({ success: true, message: 'Password updated successfully' });
  });
});

// FOR GETTING ALL SERVICES
app.get('/services', (req, res) => {
  console.log('GET /services endpoint called');
  const sql = 'SELECT * FROM tbl_services';

  db.query(sql, (err, result) => {
    if (err) {
      console.error('Services fetch error:', err);
      res.json({
        success: false,
        error: 'Failed to fetch services: ' + err.message,
      });
    } else {
      console.log('Services returned:', result.length, 'records');
      res.json({ success: true, data: result });
    }
  });
});

// FOR CREATING A NEW SERVICE
app.post('/services', (req, res) => {
  const { name, description, status, price } = req.body;

  console.log('Creating service with:', { name, description, status, price });

  const sql =
    'INSERT INTO tbl_services (fld_serviceName, fld_description, fld_serviceStatus, fld_servicePrice) VALUES (?, ?, ?, ?)';

  db.query(sql, [name, description, status, price], (err, result) => {
    if (err) {
      console.error('Database error:', err);
      res.json({
        success: false,
        error: 'Failed to create service: ' + err.message,
      });
    } else {
      console.log('Service created with ID:', result.insertId);
      res.json({
        success: true,
        message: 'Service created successfully',
        id: result.insertId,
      });
    }
  });
});

// FOR UPDATING A SERVICE
app.put('/services/:id', (req, res) => {
  const id = parseInt(req.params.id);
  const { name, description, status, price } = req.body;

  console.log('Updating service ID:', id, 'Type:', typeof id, 'with:', {
    name,
    description,
    status,
    price,
  });

  const sql =
    'UPDATE tbl_services SET fld_serviceName = ?, fld_description = ?, fld_serviceStatus = ?, fld_servicePrice = ? WHERE fld_serviceID = ?';

  db.query(sql, [name, description, status, price, id], (err, result) => {
    if (err) {
      console.error('Update error:', err);
      return res.json({
        success: false,
        error: 'Failed to update service: ' + err.message,
      });
    }

    console.log('Update result - Rows affected:', result.affectedRows);

    if (result.affectedRows === 0) {
      return res.json({ success: false, error: 'Service ID not found' });
    }

    res.json({ success: true, message: 'Service updated successfully' });
  });
});

// FOR DELETING A SERVICE
app.delete('/services/:id', (req, res) => {
  const id = parseInt(req.params.id);

  console.log('Deleting service ID:', id, 'Type:', typeof id);

  const sql = 'DELETE FROM tbl_services WHERE fld_serviceID = ?';

  db.query(sql, [id], (err, result) => {
    if (err) {
      console.error('Delete error:', err);
      return res.json({
        success: false,
        error: 'Failed to delete service: ' + err.message,
      });
    }

    console.log('Delete result - Rows affected:', result.affectedRows);

    if (result.affectedRows === 0) {
      return res.json({ success: false, error: 'Service ID not found' });
    }

    res.json({ success: true, message: 'Service deleted successfully' });
  });
});

// FOR GETTING ALL ORDERS or ORDERS BY USER ID
app.get('/orders', (req, res) => {
  const { userID } = req.query;

  let sql = `
    SELECT 
      o.fld_orderID,
      o.fld_userID,
      o.fld_serviceID,
      o.fld_adminID,
      o.fld_orderDate,
      o.fld_orderStatus,
      o.fld_amount,
      o.fld_items,
      u.fld_username,
      s.fld_serviceName
    FROM tbl_orders o
    LEFT JOIN tbl_user u ON o.fld_userID = u.fld_userID
    LEFT JOIN tbl_services s ON o.fld_serviceID = s.fld_serviceID
  `;

  // If userID is provided, filter by that userID
  if (userID) {
    sql += ` WHERE o.fld_userID = ? `;
    console.log('Fetching orders for userID:', userID);
    db.query(
      sql + 'ORDER BY o.fld_orderDate DESC',
      [parseInt(userID)],
      (err, result) => {
        if (err) {
          res.json({
            success: false,
            error: 'Failed to fetch orders: ' + err.message,
          });
        } else {
          res.json({ success: true, data: result });
        }
      }
    );
  } else {
    // Fetching all of orders for admin
    sql += ` ORDER BY o.fld_orderDate DESC`;
    console.log('Fetching all orders');
    db.query(sql, (err, result) => {
      if (err) {
        res.json({
          success: false,
          error: 'Failed to fetch orders: ' + err.message,
        });
      } else {
        console.log('Orders fetched, first order sample:', result[0]);
        res.json({ success: true, data: result });
      }
    });
  }
});

// FOR CREATING A NEW ORDER
app.post('/orders', (req, res) => {
  const { userID, serviceID, status, amount, adminID, items } = req.body;

  console.log('Creating order with:', {
    userID,
    serviceID,
    status,
    amount,
    adminID,
    items,
  });

  // Validate adminID is provided
  if (!adminID) {
    res.json({
      success: false,
      error: 'Admin ID is required to create an order.',
    });
    return;
  }

  const adminIDInt = parseInt(adminID);

  // Validate that adminID exists
  const validateAdminSql =
    'SELECT fld_adminID FROM tbl_admin WHERE fld_adminID = ?';
  db.query(validateAdminSql, [adminIDInt], (err, adminResult) => {
    if (err) {
      console.error('Admin validation error:', err);
      proceedWithOrderCreation();
      return;
    }

    console.log(
      'Admin validation result:',
      adminResult,
      'for adminID:',
      adminIDInt
    );

    if (adminResult.length === 0) {
      console.log('Admin ID not found, proceeding anyway:', adminIDInt);
      proceedWithOrderCreation();
      return;
    }

    // Admin exists, proceed with order creation
    proceedWithOrderCreation();
  });

  function proceedWithOrderCreation() {
    const sql =
      'INSERT INTO tbl_orders (fld_userID, fld_serviceID, fld_orderStatus, fld_amount, fld_adminID, fld_items) VALUES (?, ?, ?, ?, ?, ?)';

    db.query(
      sql,
      [userID, serviceID, status, amount, adminIDInt, items],
      (err, result) => {
        if (err) {
          console.error('Database error:', err);
          res.json({
            success: false,
            error: 'Failed to create order: ' + err.message,
          });
        } else {
          // Fetch the newly created order to get its ID
          // We'll find it by matching userID, adminID, serviceID and items
          const fetchSql =
            'SELECT fld_orderID FROM tbl_orders WHERE fld_userID = ? AND fld_adminID = ? AND fld_serviceID = ? AND fld_items = ? ORDER BY fld_orderID DESC LIMIT 1';
          db.query(
            fetchSql,
            [userID, adminIDInt, serviceID, items],
            (fetchErr, fetchResult) => {
              if (fetchErr || !fetchResult || fetchResult.length === 0) {
                console.error('Failed to retrieve created order ID:', fetchErr);
                // Return without ID, frontend won't be able to create report
                res.json({
                  success: true,
                  message: 'Order created successfully',
                  id: null,
                });
              } else {
                const newOrderId = fetchResult[0].fld_orderID;
                console.log('Order created with fld_orderID:', newOrderId);
                res.json({
                  success: true,
                  message: 'Order created successfully',
                  id: newOrderId,
                });
              }
            }
          );
        }
      }
    );
  }
});

// FOR UPDATING ORDER STATUS
app.put('/orders/:id', (req, res) => {
  const id = parseInt(req.params.id);
  const { status, serviceID, orderDate, amount, items } = req.body;

  process.stdout.write('\n=== PUT /orders/:id called ===\n');
  process.stdout.write(`Order ID: ${id}\n`);
  process.stdout.write(`Request body: ${JSON.stringify(req.body)}\n`);

  // Check if this is a full update (has serviceID, orderDate, amount, items) or status-only update
  const isFullUpdate = serviceID && orderDate && amount !== undefined && items;
  process.stdout.write(`Is full update: ${isFullUpdate}\n`);

  if (isFullUpdate) {
    // Full order update
    const sql =
      'UPDATE tbl_orders SET fld_serviceID = ?, fld_orderDate = ?, fld_orderStatus = ?, fld_amount = ?, fld_items = ? WHERE fld_orderID = ?';

    const params = [
      parseInt(serviceID),
      orderDate,
      status,
      parseFloat(amount),
      items,
      id,
    ];

    process.stdout.write('Executing FULL UPDATE\n');
    process.stdout.write(`SQL: ${sql}\n`);
    process.stdout.write(`Params: ${JSON.stringify(params)}\n`);

    db.query(sql, params, (err, result) => {
      if (err) {
        process.stdout.write(`UPDATE ERROR: ${err.message}\n`);
        return res.json({
          success: false,
          error: 'Failed to update order: ' + err.message,
        });
      }

      process.stdout.write(
        `UPDATE SUCCESSFUL. Rows affected: ${result.affectedRows}\n`
      );

      if (result.affectedRows === 0) {
        process.stdout.write(`Order ID not found: ${id}\n`);
        return res.json({ success: false, error: 'Order ID not found' });
      }

      res.json({ success: true, message: 'Order updated successfully' });
    });
  } else {
    // Status-only update
    const sql =
      'UPDATE tbl_orders SET fld_orderStatus = ? WHERE fld_orderID = ?';
    process.stdout.write('Executing STATUS-ONLY UPDATE\n');
    process.stdout.write(`SQL: ${sql}\n`);
    process.stdout.write(`Params: ${JSON.stringify([status, id])}\n`);

    db.query(sql, [status, id], (err, result) => {
      if (err) {
        process.stdout.write(`UPDATE ERROR: ${err.message}\n`);
        return res.json({
          success: false,
          error: 'Failed to update order: ' + err.message,
        });
      }

      process.stdout.write(
        `UPDATE SUCCESSFUL. Rows affected: ${result.affectedRows}\n`
      );

      if (result.affectedRows === 0) {
        process.stdout.write(`Order ID not found: ${id}\n`);
        return res.json({ success: false, error: 'Order ID not found' });
      }

      res.json({ success: true, message: 'Order updated successfully' });
    });
  }
});

// FOR DELETING AN ORDER
app.delete('/orders/:id', (req, res) => {
  const id = parseInt(req.params.id);

  console.log('Deleting order ID:', id);

  const sql = 'DELETE FROM tbl_orders WHERE fld_orderID = ?';

  db.query(sql, [id], (err, result) => {
    if (err) {
      console.error('Delete error:', err);
      return res.json({
        success: false,
        error: 'Failed to delete order: ' + err.message,
      });
    }

    if (result.affectedRows === 0) {
      return res.json({ success: false, error: 'Order ID not found' });
    }

    res.json({ success: true, message: 'Order deleted successfully' });
  });
});

// FOR GETTING ALL STAFF
app.get('/staff', (req, res) => {
  console.log('GET /staff endpoint called');
  const adminID = req.query.adminID;

  let sql =
    'SELECT fld_staffID, fld_adminID, fld_name, fld_email, fld_role FROM tbl_management';
  let params = [];

  if (adminID) {
    sql += ' WHERE fld_adminID = ?';
    params.push(adminID);
  }

  db.query(sql, params, (err, result) => {
    if (err) {
      console.error('Staff fetch error:', err);
      res.json({
        success: false,
        error: 'Failed to fetch staff: ' + err.message,
      });
    } else {
      console.log('Staff returned:', result.length, 'records');
      res.json({ success: true, data: result });
    }
  });
});

// FOR CREATING A NEW STAFF
app.post('/staff', (req, res) => {
  const { adminID, name, email, role } = req.body;

  console.log('Creating staff with:', { adminID, name, email, role });

  const sql =
    'INSERT INTO tbl_management (fld_adminID, fld_name, fld_email, fld_role) VALUES (?, ?, ?, ?)';

  db.query(sql, [adminID, name, email, role], (err, result) => {
    if (err) {
      console.error('Database error:', err);
      res.json({
        success: false,
        error: 'Failed to create staff: ' + err.message,
      });
    } else {
      console.log('Staff created with ID:', result.insertId);
      res.json({
        success: true,
        message: 'Staff added successfully',
        id: result.insertId,
      });
    }
  });
});

// FOR UPDATING STAFF
app.put('/staff/:id', (req, res) => {
  const id = parseInt(req.params.id);
  const { name, email, role } = req.body;

  console.log('Updating staff ID:', id, 'with:', { name, email, role });

  const sql =
    'UPDATE tbl_management SET fld_name = ?, fld_email = ?, fld_role = ? WHERE fld_staffID = ?';

  db.query(sql, [name, email, role, id], (err, result) => {
    if (err) {
      console.error('Update error:', err);
      return res.json({
        success: false,
        error: 'Failed to update staff: ' + err.message,
      });
    }

    console.log('Update result - Rows affected:', result.affectedRows);

    if (result.affectedRows === 0) {
      return res.json({ success: false, error: 'Staff ID not found' });
    }

    res.json({ success: true, message: 'Staff updated successfully' });
  });
});

// FOR DELETING STAFF
app.delete('/staff/:id', (req, res) => {
  const id = parseInt(req.params.id);

  console.log('Deleting staff ID:', id);

  const sql = 'DELETE FROM tbl_management WHERE fld_staffID = ?';

  db.query(sql, [id], (err, result) => {
    if (err) {
      console.error('Delete error:', err);
      return res.json({
        success: false,
        error: 'Failed to delete staff: ' + err.message,
      });
    }

    console.log('Delete result - Rows affected:', result.affectedRows);

    if (result.affectedRows === 0) {
      return res.json({ success: false, error: 'Staff ID not found' });
    }

    res.json({ success: true, message: 'Staff deleted successfully' });
  });
});

// FOR GETTING ALL REPORTS
app.get('/reports', (req, res) => {
  const sql = `
    SELECT r.fld_reportID, r.fld_adminID, r.fld_orderID, r.fld_dateGenerated,
           o.fld_amount, o.fld_orderStatus, u.fld_username
    FROM tbl_reports r
    LEFT JOIN tbl_orders o ON r.fld_orderID = o.fld_orderID
    LEFT JOIN tbl_user u ON o.fld_userID = u.fld_userID
    ORDER BY r.fld_dateGenerated DESC
  `;

  db.query(sql, (err, result) => {
    if (err) {
      console.error('Error fetching reports:', err);
      return res.json({
        success: false,
        error: 'Database error: ' + err.message,
      });
    }

    res.json({ success: true, data: result });
  });
});

// FOR CREATING A NEW REPORT
app.post('/reports', (req, res) => {
  const { adminID, orderID } = req.body;

  console.log('Report creation request received:', { adminID, orderID });

  const sql =
    'INSERT INTO tbl_reports (fld_adminID, fld_orderID, fld_dateGenerated) VALUES (?, ?, NOW())';

  db.query(sql, [adminID, orderID], (err, result) => {
    if (err) {
      console.error('Error creating report:', err);
      return res.json({
        success: false,
        error: 'Failed to create report: ' + err.message,
      });
    }

    console.log('Report created successfully with ID:', result.insertId);
    res.json({
      success: true,
      message: 'Report created successfully',
      id: result.insertId,
    });
  });
});

app.listen(8081, '0.0.0.0', () => {
  console.log('Server running on port 8081');
});
